services:
  - type: web
    name: carbon-credit-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # Set this securely in the Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
